from __future__ import annotations
import pandas as pd
QUESTIONS=[
('Q1','Memory','What kinds of old photos and visual assets do users struggle to retrieve?',['asset_type']),('Q2','Memory','What information do users actually remember about those assets?',['memory_type']),('Q3','Memory','What information have they forgotten?',['outcome']),('Q4','Query formation','How do users formulate an initial search when memory is incomplete?',['failure_stage']),('Q5','Query formation','Which remembered clues are omitted from the initial query?',['memory_type']),('Q6','Memory','Which memory types produce different retrieval behaviours?',['memory_type','workaround']),('Q7','Failure','Where does the retrieval journey break down?',['failure_stage']),('Q8','Retrieval behaviour','What happens after the first unsuccessful attempt?',['workaround','outcome']),('Q9','Retrieval behaviour','How do users refine or reformulate their searches?',['workaround']),('Q10','Retrieval behaviour','Which refinement behaviours help, fail, or loop?',['workaround','outcome']),('Q11','Failure','Why do users fail when candidates appear?',['failure_stage']),('Q12','Retrieval behaviour','What helps recognise or verify the correct photograph?',['outcome']),('Q13','Workarounds','Which external workarounds do users employ?',['workaround']),('Q14','Workarounds','What do successful workarounds reveal?',['workaround']),('Q15','Opportunity discovery','Which failure mechanisms recur across independent sources?',['themes']),('Q16','Opportunity discovery','Which findings may result from source-selection bias?',['source_platform']),('Q17','Opportunity discovery','Which existing capabilities address problems?',['themes']),('Q18','Opportunity discovery','Which potential gaps remain despite capabilities?',['themes']),('Q19','Opportunity discovery','Which findings are contradicted?',['outcome']),('Q20','Opportunity discovery','Which questions cannot be answered through public feedback?',[]),('Q21','Opportunity discovery','Which opportunities could improve verified retrieval success?',['themes']),('Q22','Opportunity discovery','Which problems are feasible to reproduce and test in an MVP?',['themes'])]
def questions(evidence:pd.DataFrame)->pd.DataFrame:
    rel=evidence[evidence.relevance.isin(['DIRECT','RELATED'])]; rows=[]
    for q,g,text,fields in QUESTIONS:
        hits=rel if fields else rel.iloc[0:0]
        if q in ['Q12','Q14','Q19','Q20']: hits=rel.iloc[0:0] # intentional evidence gap: outcomes/verification rarely reported
        ids='|'.join(hits.record_id.head(8)); n=len(hits)
        answer=('Insufficient public evidence — requires primary research.' if n==0 else f'Directional public evidence from {n} relevant records; inspect linked evidence before treating as a population estimate.')
        rows.append(dict(question_id=q,group=g,question=text,answer=answer,evidence_count=n,denominator=len(rel),evidence_ids=ids,confidence='Low' if n<3 else 'Directional',interview_follow_up='Ask participants to reconstruct a specific recent retrieval episode, including clues, attempts, response and outcome.'))
    return pd.DataFrame(rows)
def themes(evidence:pd.DataFrame)->pd.DataFrame:
    rel=evidence[evidence.relevance.isin(['DIRECT','RELATED'])]; rows=[]
    for t in sorted({x for s in rel.themes for x in s.split('|')}):
        f=rel[rel.themes.str.contains(t,regex=False)]; rows.append(dict(theme=t,evidence_count=len(f),rich_count=int(f.evidence_depth.isin(['E1','E2']).sum()),source_count=f.source_platform.nunique(),source_distribution=' | '.join(f.source_platform.value_counts().index),record_ids='|'.join(f.record_id),definition='A provisional mechanism label assigned by deterministic taxonomy plus semantic-cluster review.',contradictions='Some records report available workarounds or different results; public feedback cannot establish prevalence.',research_gap='Validate with observed retrieval tasks and account/device context.'))
    return pd.DataFrame(rows)
def hypotheses(theme_df:pd.DataFrame)->pd.DataFrame:
    rows=[]
    for i,r in theme_df.reset_index(drop=True).iterrows(): rows.append(dict(hypothesis_id=f'H{i+1}',theme=r.theme,status='Directionally supported' if r.source_count>1 else 'Emerging',statement=f'The {r.theme} mechanism may reduce verified retrieval success in a subset of vague-memory attempts.',supporting_ids=r.record_ids,contradictory_evidence=r.contradictions,interview_question='Reconstruct the last time this situation occurred; what clue did you have but not use, and why?',potential_outcome='Higher verified retrieval success; lower time-to-verified-retrieval.'))
    return pd.DataFrame(rows)
