"""Editorial synthesis for the consolidated, source-neutral Retrieval Cases dataset.

Editorial Q&A in the workbook is used as a research-planning aid only. It is
not presented as an interview transcript or counted as a retrieval episode.
"""
from __future__ import annotations
import pandas as pd

FINDINGS = [
 {"id":"F1","title":"Context and relationships are often remembered but weakly expressed in the first search","observed":"Cases describe a distinctive family object, a pet, a trip, an event, a place category, or a remembered period rather than a single object word.","mechanism":"Possible mismatch between relational or temporal memory and the cues people choose or can apply in search.","supporting_ids":["S01","C08","S08","S10","S12","S13"],"contradictory_ids":["S03","S05"],"opportunity":"Test context-led starting points that let people express event, relationship, period, and collection clues together.","question":"When people know an event or relationship, which clues do they expect to combine and which do they omit?","metric":"Verified target retrieval rate, time to target, and clue coverage."},
 {"id":"F2","title":"Related-image retrieval is an explicit but unvalidated need","observed":"One case asks whether a newer photograph of a distinctive object can locate an older one, and another seeks a visually specific plant image.","mechanism":"People may hold a visual reference when they lack a name, date, or usable text clue.","supporting_ids":["S01","S13"],"contradictory_ids":["S03","S05"],"opportunity":"Compare reference-image-assisted retrieval with text and timeline routes before assuming a new capability is needed.","question":"Does a reference image improve retrieval over the best existing query and browsing path?","metric":"First-candidate relevance and verified success by retrieval route."},
 {"id":"F3","title":"Exact text and screenshot retrieval can diverge from people’s expectations","observed":"Cases describe literal screenshot text returning broad associations, inconsistent visible-word retrieval, and document-text results changing over time.","mechanism":"A possible gap between expected literal matching, indexing state, and ranked results. The evidence does not diagnose the cause.","supporting_ids":["C20","C18","C07","S15"],"contradictory_ids":["C20"],"opportunity":"Test clearer literal-text refinement, result explanation, and text-specific search guidance against the current experience.","question":"When exact text is remembered, do people recognize and successfully use the available literal-text path?","metric":"Screenshot or document retrieval success, reformulations per task, and confidence in result meaning."},
 {"id":"F4","title":"A useful candidate may not provide a smooth path to the surrounding timeline","observed":"Cases report scrolling through a remembered period, finding one vacation day but not adjacent dates, and wanting chronological results after an irrelevant result set.","mechanism":"Candidate inspection may not connect clearly to nearby photos, dates, or trip context.","supporting_ids":["C08","S08","S09","S14"],"contradictory_ids":["S03"],"opportunity":"Compare candidate-to-date and candidate-to-nearby-photo navigation with ordinary chronological browsing.","question":"After a near match, where do people expect to go next and can they reach that context without restarting?","metric":"Time from first useful candidate to verified target and near-miss abandonment."},
 {"id":"F5","title":"Query reformulation helps in some cases but can become high effort","observed":"Cases show multiple clue variants, quoted text, alternative result ordering, copies, and switching search modes.","mechanism":"People may lack feedback about whether a query is too broad, interpreted differently, or constrained by asset availability.","supporting_ids":["C08","C20","S07","C18","S20"],"contradictory_ids":["S03","S05"],"opportunity":"Test lightweight reformulation guidance and route comparison rather than presuming an automatic query rewrite.","question":"Which feedback changes the next action without increasing unproductive query loops?","metric":"Queries or refinements per verified success and task completion time."},
 {"id":"F6","title":"Recognition and verification are under-recorded","observed":"Some accounts report finding a result, while many unresolved accounts do not establish whether the intended asset existed, appeared, or was recognized.","mechanism":"The record usually omits the candidate set, asset state, and the cues used to confirm a match.","supporting_ids":["C08","S03","S06","S08"],"contradictory_ids":["S10","S13"],"opportunity":"Instrument or observe target confirmation before interpreting a search complaint as a retrieval-model failure.","question":"How do people decide a candidate is the correct photo, and what evidence do they use?","metric":"Observed target verification rate and false-positive candidate selection."},
 {"id":"F7","title":"Successful workarounds reveal competing intervention directions","observed":"Reported workarounds include chronology browsing, exact-text reformulation, saving a copy, device or folder checks, and switching search modes.","mechanism":"A workaround can signal discoverability, navigation, availability, or result-interpretation friction; it does not prove a missing feature.","supporting_ids":["C08","C20","S07","S17","S19","S20"],"contradictory_ids":["S10","S12"],"opportunity":"Test guidance, diagnostic, navigation, and retrieval-assist interventions side by side rather than preselecting an MVP.","question":"Which workaround is fastest, understandable, and reliable for a consented retrieval task?","metric":"Verified recovery rate, route-switch rate, and perceived effort."},
]

QUESTIONS = [
 ("Memory","Which contextual, relational, temporal, text, and visual clues are remembered before search?","The consolidated cases contain each clue type, but not a representative frequency.",["S01","C08","C20","S08"]),
 ("Journey","Which stage fails first: query formulation, result interpretation, context navigation, or asset availability?","The recorded accounts suggest several stages; direct observation is required to diagnose a specific mechanism.",["C20","S08","S18","S19"]),
 ("Workarounds","Which workarounds reach a verified target with acceptable effort?","Several routes are reported, but most outcomes are self-reported and not independently observed.",["C08","C20","S07","S20"]),
 ("Validation","What must be checked before calling a retrieval task a product failure?","Confirm target existence, account and backup state, query route, candidate set, and recognition of the target.",["S18","S19","S10"]),
]

def evidence_for(finding:dict, records:pd.DataFrame)->pd.DataFrame:
 return records[records.case_id.isin(finding['supporting_ids'])]

def validate_editorial_ids(records:pd.DataFrame)->list[str]:
 ids=set(records.case_id)
 used={case for finding in FINDINGS for case in finding['supporting_ids']+finding['contradictory_ids']}
 used|={case for _,_,_,refs in QUESTIONS for case in refs}
 return sorted(used-ids)
